// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: myMsg.proto

package myMsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command int32

const (
	Command_CtoSLoginType     Command = 0  // 登入
	Command_StoCLoginType     Command = 1  // 登入回應
	Command_CtoSHeartBeatType Command = 9  // ping
	Command_StoCHeartBeatType Command = 10 // pong
)

// Enum value maps for Command.
var (
	Command_name = map[int32]string{
		0:  "CtoSLoginType",
		1:  "StoCLoginType",
		9:  "CtoSHeartBeatType",
		10: "StoCHeartBeatType",
	}
	Command_value = map[string]int32{
		"CtoSLoginType":     0,
		"StoCLoginType":     1,
		"CtoSHeartBeatType": 9,
		"StoCHeartBeatType": 10,
	}
)

func (x Command) Enum() *Command {
	p := new(Command)
	*p = x
	return p
}

func (x Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command) Descriptor() protoreflect.EnumDescriptor {
	return file_myMsg_proto_enumTypes[0].Descriptor()
}

func (Command) Type() protoreflect.EnumType {
	return &file_myMsg_proto_enumTypes[0]
}

func (x Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command.Descriptor instead.
func (Command) EnumDescriptor() ([]byte, []int) {
	return file_myMsg_proto_rawDescGZIP(), []int{0}
}

// ping
type CtoSHeartBeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CtoSHeartBeat) Reset() {
	*x = CtoSHeartBeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myMsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CtoSHeartBeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtoSHeartBeat) ProtoMessage() {}

func (x *CtoSHeartBeat) ProtoReflect() protoreflect.Message {
	mi := &file_myMsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtoSHeartBeat.ProtoReflect.Descriptor instead.
func (*CtoSHeartBeat) Descriptor() ([]byte, []int) {
	return file_myMsg_proto_rawDescGZIP(), []int{0}
}

// pong
type StoCHeartBeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StoCHeartBeat) Reset() {
	*x = StoCHeartBeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myMsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoCHeartBeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoCHeartBeat) ProtoMessage() {}

func (x *StoCHeartBeat) ProtoReflect() protoreflect.Message {
	mi := &file_myMsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoCHeartBeat.ProtoReflect.Descriptor instead.
func (*StoCHeartBeat) Descriptor() ([]byte, []int) {
	return file_myMsg_proto_rawDescGZIP(), []int{1}
}

// client登入
type CtoSLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CtoSLogin) Reset() {
	*x = CtoSLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myMsg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CtoSLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtoSLogin) ProtoMessage() {}

func (x *CtoSLogin) ProtoReflect() protoreflect.Message {
	mi := &file_myMsg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtoSLogin.ProtoReflect.Descriptor instead.
func (*CtoSLogin) Descriptor() ([]byte, []int) {
	return file_myMsg_proto_rawDescGZIP(), []int{2}
}

// server回應登入
type StoCLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User    *User `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Balance int32 `protobuf:"varint,2,opt,name=Balance,proto3" json:"Balance,omitempty"`
}

func (x *StoCLogin) Reset() {
	*x = StoCLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myMsg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoCLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoCLogin) ProtoMessage() {}

func (x *StoCLogin) ProtoReflect() protoreflect.Message {
	mi := &file_myMsg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoCLogin.ProtoReflect.Descriptor instead.
func (*StoCLogin) Descriptor() ([]byte, []int) {
	return file_myMsg_proto_rawDescGZIP(), []int{3}
}

func (x *StoCLogin) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *StoCLogin) GetBalance() int32 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int32  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	UserPwd string `protobuf:"bytes,2,opt,name=UserPwd,proto3" json:"UserPwd,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myMsg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_myMsg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_myMsg_proto_rawDescGZIP(), []int{4}
}

func (x *User) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *User) GetUserPwd() string {
	if x != nil {
		return x.UserPwd
	}
	return ""
}

var File_myMsg_proto protoreflect.FileDescriptor

var file_myMsg_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6d, 0x79, 0x4d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d,
	0x79, 0x4d, 0x73, 0x67, 0x22, 0x0f, 0x0a, 0x0d, 0x43, 0x74, 0x6f, 0x53, 0x48, 0x65, 0x61, 0x72,
	0x74, 0x42, 0x65, 0x61, 0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x53, 0x74, 0x6f, 0x43, 0x48, 0x65, 0x61,
	0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x22, 0x0b, 0x0a, 0x09, 0x43, 0x74, 0x6f, 0x53, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x22, 0x46, 0x0a, 0x09, 0x53, 0x74, 0x6f, 0x43, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x12, 0x1f, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x6d, 0x79, 0x4d, 0x73, 0x67, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x38, 0x0a, 0x04, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x55,
	0x73, 0x65, 0x72, 0x50, 0x77, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x55, 0x73,
	0x65, 0x72, 0x50, 0x77, 0x64, 0x2a, 0x5d, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x12, 0x11, 0x0a, 0x0d, 0x43, 0x74, 0x6f, 0x53, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x74, 0x6f, 0x43, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x43, 0x74, 0x6f, 0x53, 0x48, 0x65,
	0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x10, 0x09, 0x12, 0x15, 0x0a,
	0x11, 0x53, 0x74, 0x6f, 0x43, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x10, 0x0a, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_myMsg_proto_rawDescOnce sync.Once
	file_myMsg_proto_rawDescData = file_myMsg_proto_rawDesc
)

func file_myMsg_proto_rawDescGZIP() []byte {
	file_myMsg_proto_rawDescOnce.Do(func() {
		file_myMsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_myMsg_proto_rawDescData)
	})
	return file_myMsg_proto_rawDescData
}

var file_myMsg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_myMsg_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_myMsg_proto_goTypes = []interface{}{
	(Command)(0),          // 0: myMsg.Command
	(*CtoSHeartBeat)(nil), // 1: myMsg.CtoSHeartBeat
	(*StoCHeartBeat)(nil), // 2: myMsg.StoCHeartBeat
	(*CtoSLogin)(nil),     // 3: myMsg.CtoSLogin
	(*StoCLogin)(nil),     // 4: myMsg.StoCLogin
	(*User)(nil),          // 5: myMsg.User
}
var file_myMsg_proto_depIdxs = []int32{
	5, // 0: myMsg.StoCLogin.User:type_name -> myMsg.User
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_myMsg_proto_init() }
func file_myMsg_proto_init() {
	if File_myMsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_myMsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CtoSHeartBeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_myMsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoCHeartBeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_myMsg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CtoSLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_myMsg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoCLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_myMsg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_myMsg_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_myMsg_proto_goTypes,
		DependencyIndexes: file_myMsg_proto_depIdxs,
		EnumInfos:         file_myMsg_proto_enumTypes,
		MessageInfos:      file_myMsg_proto_msgTypes,
	}.Build()
	File_myMsg_proto = out.File
	file_myMsg_proto_rawDesc = nil
	file_myMsg_proto_goTypes = nil
	file_myMsg_proto_depIdxs = nil
}
